/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_Battery
#define HEADER_Battery

#include "BatteryMeter.h"

void Battery_getData(double* level, ACPresence* isOnAC);


#endif
